#/*******************************************************************************
#* Licensed Materials - Property of HCL 
#* (c) Copyright HCL Technologies Ltd. 2021. All Rights Reserved. 
#
#* Note to U.S. Government Users Restricted Rights:
#* Use, duplication or disclosure restricted by GSA ADP Schedule
#**************************************************************/
ARG REGISTRY
ARG VERSION
FROM ${REGISTRY}/aida-ad:${VERSION}

#Exposing at port 5000
EXPOSE 5000


# command to run on container start  
CMD python -m server.py 
