#/*******************************************************************************
#* Licensed Materials - Property of HCL 
#* (c) Copyright HCL Technologies Ltd. 2023. All Rights Reserved. 
#
#* Note to U.S. Government Users Restricted Rights:
#* Use, duplication or disclosure restricted by GSA ADP Schedule
#**************************************************************/

ARG REGISTRY
ARG VERSION
FROM ${REGISTRY}aida-exporter:${VERSION} AS base

WORKDIR /usr/src/app

FROM base AS dev
RUN pip install debugpy

CMD python -m debugpy  --listen 0.0.0.0:5678 exporter.py

FROM base AS debug

RUN pip install debugpy

CMD python -m debugpy --wait-for-client --listen 0.0.0.0:5678 exporter.py

FROM base AS release
CMD python3 ./exporter.pyc 