#/*******************************************************************************
#* Licensed Materials - Property of HCL 
#* (c) Copyright HCL Technologies Ltd. 2021. All Rights Reserved. 
#
#* Note to U.S. Government Users Restricted Rights:
#* Use, duplication or disclosure restricted by GSA ADP Schedule
#**************************************************************/
ARG REGISTRY
ARG VERSION
FROM ${REGISTRY}/aida-redis:${VERSION}
EXPOSE 6379

USER 0

COPY ./redis/redis.conf /usr/local/etc/redis/redis.conf
COPY ./redis/redis.key /etc/ssl/
COPY ./redis/redis.crt /etc/ssl/
COPY ./redis/ca.pem /etc/ssl/certs/

RUN chown -R default:users ./redis-6.2.1 \
    && chown -R default:users /usr/local/etc/redis/ \
    && chown -R default:users /etc/ssl/ \
    && chmod -R 0775 ./redis-6.2.1 \
    && chmod -R 0775 /usr/local/etc/redis/ \
    && chmod -R 0775 /etc/ssl/
	
USER default:users

CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
