FROM quay.io/keycloak/keycloak:22.0.5
EXPOSE 8080

ENV KEYCLOAK_PATH opt/keycloak
ENV KEYCLOAK_USER_MANAGER ${KEYCLOAK_PATH}/bin/kcadm.sh
ENV KEYCLOAK_ADMIN admin
ENV KEYCLOAK_ADMIN_PASSWORD admin

ENV KC_HOSTNAME_STRICT false
ENV KC_PROXY_ADDRESS_FORWARDING true

COPY keycloak/aida-realm.json ${KEYCLOAK_PATH}/data/import/aida-realm.json
COPY keycloak/base_themes ${KEYCLOAK_PATH}/themes/
COPY keycloak/keycloak.conf ${KEYCLOAK_PATH}/conf/keycloak.conf

RUN mkdir -p ${KEYCLOAK_PATH}/data/h2
RUN chmod -R 777 ${KEYCLOAK_PATH}/data/h2

RUN ${KEYCLOAK_PATH}/bin/kc.sh build

ENTRYPOINT ${KEYCLOAK_PATH}/bin/kc.sh start --import-realm --auto-build


