#/*******************************************************************************
#* Licensed Materials - Property of HCL 
#* (c) Copyright HCL Technologies Ltd. 2021. All Rights Reserved. 
#
#* Note to U.S. Government Users Restricted Rights:
#* Use, duplication or disclosure restricted by GSA ADP Schedule
#**************************************************************/
ARG REGISTRY
ARG VERSION
FROM ${REGISTRY}/aida-email:${VERSION}

WORKDIR /usr/src/app

EXPOSE 5000

CMD python3 ./sendMail.py
