#/*******************************************************************************
#* Licensed Materials - Property of HCL 
#* (c) Copyright HCL Technologies Ltd. 2021. All Rights Reserved. 
#
#* Note to U.S. Government Users Restricted Rights:
#* Use, duplication or disclosure restricted by GSA ADP Schedule
#**************************************************************/
ARG REGISTRY
ARG VERSION
FROM ${REGISTRY}/aida-exporter:${VERSION}

WORKDIR /usr/src/app
CMD nohup python3 ./exporter.py